# Generated by Django 6.0.2 on 2026-02-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL')),
                ('fee_per_day', models.DecimalField(decimal_places=2, help_text='LKR per day', max_digits=10)),
                ('languages', models.JSONField(default=list)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('experience', models.CharField(blank=True, help_text='e.g. 5 Years', max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
