# Generated by Django 6.0.2 on 2026-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='123 Tourism Drive, Colombo 03, Sri Lanka')),
                ('email_1', models.EmailField(default='hello@tripzio.com', max_length=254)),
                ('email_2', models.EmailField(default='support@tripzio.com', max_length=254)),
                ('phone_1', models.CharField(default='+94 11 234 5678', max_length=20)),
                ('phone_2', models.CharField(default='+94 77 123 4567', max_length=20)),
                ('map_url', models.URLField(default='https://images.unsplash.com/photo-1569668723429-9fb7e19bd65e?auto=format&fit=crop&q=80&w=1000')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message'},
        ),
    ]
