# Generated by Django 5.2.6 on 2026-02-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(blank=True, default='+94771234567', max_length=20),
        ),
    ]
