# Generated by Django 6.0.2 on 2026-02-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('full_description', models.TextField()),
                ('image', models.URLField(help_text='Main cover image URL')),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of experiences')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('best_season', models.CharField(max_length=100)),
                ('seasons', models.JSONField(default=list, help_text='Month indices (0=Jan ... 11=Dec) when best to visit')),
                ('popular_activities', models.JSONField(default=list)),
                ('coordinates_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('coordinates_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('images', models.JSONField(default=list, help_text='List of gallery image URLs')),
                ('category', models.CharField(choices=[('Beaches', 'Beaches'), ('Mountains', 'Mountains'), ('Cultural', 'Cultural'), ('Wildlife', 'Wildlife'), ('Historical', 'Historical')], max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
    ]
