# Generated by Django 6.0.2 on 2026-02-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('STAY', 'Stay'), ('TOUR', 'Tour')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='LKR per day/night/person', max_digits=12)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('Car', 'Car'), ('Van', 'Van'), ('SUV', 'SUV'), ('Bus', 'Bus'), ('Tuk-Tuk', 'Tuk-Tuk')], max_length=20)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('driver_included', models.BooleanField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('air_conditioned', models.BooleanField(blank=True, null=True)),
                ('stay_type', models.CharField(blank=True, choices=[('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Villa', 'Villa'), ('Guesthouse', 'Guesthouse'), ('Hostel', 'Hostel')], max_length=20)),
                ('rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('tour_type', models.CharField(blank=True, choices=[('Cultural', 'Cultural'), ('Wildlife', 'Wildlife'), ('Whale Watching', 'Whale Watching'), ('Mountain', 'Mountain'), ('Temple', 'Temple'), ('Beach', 'Beach'), ('Adventure', 'Adventure')], max_length=30)),
                ('group_size', models.CharField(blank=True, max_length=50)),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('included', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('url', models.URLField(blank=True, help_text='External URL if not uploading a file')),
                ('order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
