# Generated by Django 5.2.6 on 2026-02-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
            ],
            options={
                'verbose_name': 'Stay',
                'verbose_name_plural': 'Stays',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('listings.listing',),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('Cultural', 'Cultural'), ('Wildlife', 'Wildlife'), ('Whale Watching', 'Whale Watching'), ('Mountain', 'Mountain'), ('Temple', 'Temple'), ('Beach', 'Beach'), ('Adventure', 'Adventure'), ('Round Tour', 'Round Tour')], max_length=30),
        ),
    ]
