# Generated by Django 5.2.6 on 2026-02-23 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_stay_tour_vehicle_alter_listing_tour_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='LKR per person/package', max_digits=12)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('duration', models.CharField(help_text='e.g., 7 Days / 6 Nights', max_length=50)),
                ('group_size', models.CharField(blank=True, max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('included', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundTourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='round_tours/')),
                ('url', models.URLField(blank=True, help_text='External URL if not uploading a file')),
                ('order', models.PositiveIntegerField(default=0)),
                ('round_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.roundtour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
